githubRepoOwner: batfish
githubRepoName: lab-validation
githubHost: github.com
githubRemote: origin
githubBranch: main
requireChecks: true
requireApproval: false
mergeMethod: rebase
mergeQueue: false
forceFetchTags: false
showPrTitlesInStack: false
branchPushIndividually: false
