[mypy]
python_version = 3.10
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = True

[mypy-cerberus.*]
ignore_missing_imports = True

[mypy-netmiko.*]
ignore_missing_imports = True

[mypy-paramiko.*]
ignore_missing_imports = True

[mypy-ttp.*]
ignore_missing_imports = True
