# Ruff configuration
# See https://docs.astral.sh/ruff/configuration/

# Same as Black line length
line-length = 88

# Python version compatibility
target-version = "py310"

[lint]
# Enable rules that replace the tools we're removing:
# - F: Pyflakes (basic linting)
# - E, W: pycodestyle errors and warnings
# - I: isort (import sorting)
# - UP: pyupgrade (modern Python idioms, but be selective)
select = ["F", "E", "W", "I", "UP031", "UP008"]

# Ignore some rules that might be too strict for existing code
ignore = [
    "E501",  # Line too long (handled by formatter)
    "E741",  # Ambiguous variable name (too restrictive for this codebase)
    "E722",  # Do not use bare except (existing code pattern)
]

[lint.isort]
# Match the existing isort configuration (black-compatible)
force-single-line = false
combine-as-imports = true
known-first-party = ["lab_validation", "lab_tests"]

[format]
# Use Black-compatible formatting
quote-style = "double"
indent-style = "space"
