Building configuration...

Current configuration:
!
frr version 10.5.4
frr defaults traditional
hostname s2
log syslog informational
log facility local4
zebra nexthop-group keep 1
fpm address 127.0.0.1
no fpm use-next-hop-groups
agentx
no service integrated-vtysh-config
!
ip prefix-list DEFAULT_IPV4 seq 5 permit 0.0.0.0/0
ip prefix-list PL_LoopbackV4 seq 5 permit 2.2.2.2/32
!
ipv6 prefix-list DEFAULT_IPV6 seq 5 permit ::/0
!
route-map ALLOW_LIST_DEPLOYMENT_ID_0_V4 permit 65535
 set community 5060:12345 additive
exit
!
route-map ALLOW_LIST_DEPLOYMENT_ID_0_V6 permit 65535
 set community 5060:12345 additive
exit
!
route-map CHECK_IDF_ISOLATION permit 10
exit
!
route-map FROM_BGP_PEER_V4 permit 10
 call ALLOW_LIST_DEPLOYMENT_ID_0_V4
 on-match next
exit
!
route-map FROM_BGP_PEER_V4 permit 11
 match community allow_list_default_community
exit
!
route-map FROM_BGP_PEER_V4 permit 100
exit
!
route-map FROM_BGP_PEER_V6 permit 1
 on-match next
 set ipv6 next-hop prefer-global
exit
!
route-map FROM_BGP_PEER_V6 permit 10
 call ALLOW_LIST_DEPLOYMENT_ID_0_V6
 on-match next
exit
!
route-map FROM_BGP_PEER_V6 permit 11
 match community allow_list_default_community
exit
!
route-map FROM_BGP_PEER_V6 permit 100
exit
!
route-map RM_SET_SRC permit 10
 set src 2.2.2.2
exit
!
route-map TO_BGP_PEER_V4 permit 100
 call CHECK_IDF_ISOLATION
exit
!
route-map TO_BGP_PEER_V6 permit 100
 call CHECK_IDF_ISOLATION
exit
!
password zebra
enable password zebra
!
router bgp 65002
 bgp router-id 2.2.2.2
 bgp suppress-fib-pending
 bgp log-neighbor-changes
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 bgp bestpath as-path multipath-relax
 neighbor PEER_V4 peer-group
 neighbor PEER_V6 peer-group
 neighbor 192.168.12.0 remote-as 65001
 neighbor 192.168.12.0 peer-group PEER_V4
 neighbor 192.168.12.0 description s1
 neighbor 192.168.12.0 timers connect 10
 neighbor 192.168.12.2 remote-as 65001
 neighbor 192.168.12.2 peer-group PEER_V4
 neighbor 192.168.12.2 description s1
 neighbor 192.168.12.2 timers connect 10
 !
 address-family ipv4 unicast
  network 2.2.2.2/32
  neighbor PEER_V4 soft-reconfiguration inbound
  neighbor PEER_V4 route-map FROM_BGP_PEER_V4 in
  neighbor PEER_V4 route-map TO_BGP_PEER_V4 out
  neighbor 192.168.12.0 activate
  neighbor 192.168.12.2 activate
 exit-address-family
 !
 address-family ipv6 unicast
  neighbor PEER_V6 soft-reconfiguration inbound
  neighbor PEER_V6 route-map FROM_BGP_PEER_V6 in
  neighbor PEER_V6 route-map TO_BGP_PEER_V6 out
 exit-address-family
exit
!
bgp community-list standard allow_list_default_community seq 5 permit no-export
bgp community-list standard allow_list_default_community seq 10 permit 5060:12345
!
ip protocol bgp route-map RM_SET_SRC
!
ip nht resolve-via-default
!
ipv6 nht resolve-via-default
!
end
