name: Daily CI

on:
  schedule:
    - cron: "0 15 * * *" # 8AM Pacific; daily
  workflow_dispatch: # Allow manual triggering
  push:
    branches: [ add-daily-ci-workflow ] # Temporary for testing

jobs:
  # Temporary test job to simulate failure (remove after testing)
  test-failure:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate failure for testing
        run: |
          echo "Testing Slack notification on failure"
          exit 1

  # Run the existing CI workflow
  ci:
    uses: ./.github/workflows/ci.yml
    needs: test-failure

  # Send Slack notification on failure
  notify-slack-on-failure:
    needs: [test-failure, ci]
    if: always() && (needs.test-failure.result == 'failure' || needs.ci.result == 'failure')
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification on failure
        uses: slackapi/slack-github-action@v2.1.0
        with:
          webhook: ${{ secrets.LAB_VALIDATION_SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "text": "*Lab validation daily CI workflow failed*",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Lab validation daily CI workflow failed*"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Workflow:*\n${{ github.workflow }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Status:*\nFailed"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Trigger:*\n${{ github.event_name == 'schedule' && 'Daily scheduled run' || 'Manual trigger' }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:*\n${{ github.repository }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Commit:* ${{ github.sha }}\n*Branch:* ${{ github.ref_name }}"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Workflow Run in GitHub Actions"
                      },
                      "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }
